// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxjntcqhtwhdlfkndkqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4am50Y3FodHdoZGxma25ka3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MTA0NTksImV4cCI6MjA2OTQ4NjQ1OX0.ptt8bU2lpWS6GH2KK71q582g8W4O01ptH-xJcnBBw0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});